# Generated by Django 2.0.6 on 2018-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcount',
            name='name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
