# Generated by Django 2.0.6 on 2018-07-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='VisitCount',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
